# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('coste', models.IntegerField(default=0)),
                ('cliente', models.CharField(max_length=70)),
                ('obs', models.TextField(max_length=200)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('user', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateTimeField(null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('abierto', models.BooleanField(default=True)),
                ('moto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=10)),
                ('obs', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Parking'),
        ),
    ]
