# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('dueno', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('cliente', models.CharField(max_length=70)),
                ('obs', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago',
            field=models.IntegerField(),
        ),
    ]
