# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191023_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Parking'),
        ),
    ]
