# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191030_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='coste',
            field=models.IntegerField(default=0),
        ),
    ]
