# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contrato_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dueno',
        ),
    ]
